### ISSUE TITLE
WHAM Version Conflicts with DPVO (Same Issue as #100)

### ISSUE THREAD

**Issue by Ruslan0110** [yohanshin/WHAM#136]
I am facing a compatibility issue when trying to use WHAM and DPVO together. After installing DPVO, the WHAM environment gets modified, making WHAM unable to run properly. The main issues seem to be related to NumPy version conflicts, MMCV/MMPose incompatibilities, and PyTorch/CUDA mismatches.

1. NumPy Conflict: DPVO upgrades NumPy to 2.x, while WHAM and its dependencies expect NumPy 1.x, leading to binary incompatibility errors.
2. MMCV and MMPose Issues: WHAM requires mmcv-full<=1.5.0, but DPVO installs 1.6.2, causing import errors in MMPose.
3. CUDA and PyTorch Issues: After installing DPVO, running WHAM results in CUDA runtime errors (CUBLAS_STATUS_INVALID_VALUE).
4. MMPose Import Issue: WHAM fails to import inference_topdown and init_model from MMPose after DPVO installation.
5. Unset LD_LIBRARY_PATH Not Helping: I tried running unset LD_LIBRARY_PATH, but it does not resolve the issue. The conflicts persist, and WHAM remains broken.

**Questions:**

- Has anyone successfully integrated WHAM and DPVO in the same environment without breaking dependencies?

- Is there a recommended way to resolve version conflicts between these two frameworks?

- Would it be better to use separate Conda environments for each, or is there a way to align their dependencies?

**Comment by Lingling006688** [comment]
Hi, I am facing the same issue. Did you solve it? Thank you in advance. @Ruslan0110

**Comment by snake-head** [comment]
I ran into the same issue and managed to get a successful installation by adjusting the environment setup. The most critical change was upgrading the Python version from 3.9 to 3.10.

Here are the complete, tested steps to successfully install both wham and DPVO:

```
# 1. Create and activate the conda environment
conda create -n wham python=3.10
conda activate wham

# 2. Install PyTorch and related tools
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu113_pyt1110/download.html

# 3. Install DPVO dependencies and compile
cd third-party/DPVO
wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
unzip eigen-3.4.0.zip -d thirdparty && rm -rf eigen-3.4.0.zip
conda install pytorch-scatter=2.0.9 -c rusty1s
conda install cudatoolkit-dev=11 -c conda-forge
conda install mkl=2024.0
pip install numpy==1.22.3
conda install -c conda-forge gxx=9.5
pip install .

# 4. Return to the project root and install WHAM requirements
cd ../..
pip install -r requirements.txt
```

**Comment by astonastonaston** [comment]
> I ran into the same issue and managed to get a successful installation by adjusting the environment setup. The most critical change was upgrading the Python version from 3.9 to 3.10.
> 
> Here are the complete, tested steps to successfully install both wham and DPVO:
> 
> ```
> # 1. Create and activate the conda environment
> conda create -n wham python=3.10
> conda activate wham
> 
> # 2. Install PyTorch and related tools
> conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
> conda install -c fvcore -c iopath -c conda-forge fvcore iopath
> pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu113_pyt1110/download.html
> 
> # 3. Install DPVO dependencies and compile
> cd third-party/DPVO
> wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
> unzip eigen-3.4.0.zip -d thirdparty && rm -rf eigen-3.4.0.zip
> conda install pytorch-scatter=2.0.9 -c rusty1s
> conda install cudatoolkit-dev=11 -c conda-forge
> conda install mkl=2024.0
> pip install numpy==1.22.3
> conda install -c conda-forge gxx=9.5
> pip install .
> 
> # 4. Return to the project root and install WHAM requirements
> cd ../..
> pip install -r requirements.txt
> ```

Solved my problem. Thank you!
